
def format (diff:str, indient='  '):
    print(len(diff))
    # print(diff[0])

    return diff[0]

#test = "[[(0, 'common'), ((1, 'setting1'), ('Value 1', 'Value 1')), ((1, 'setting2'), (200, None)), ((1, 'setting3'), (True, None)), (1, 'setting6'), ((2, 'key'), ('value', 'value')), (2, 'doge'), ((3, 'wow'), ('', 'so much')), (0, 'group1'), ((1, 'baz'), ('bas', 'bars')), ((1, 'foo'), ('bar', 'bar')), ((1, 'nest'), ({'key': 'value'}, [...])), ((0, 'group2'), ({'abc': 12345, 'deep': {'id': 45}}, [...])), ((0, 'group3'), (None, [...]))], [(0, 'common'), ((1, 'setting1'), ('Value 1', 'Value 1')), ((1, 'setting2'), (200, None)), ((1, 'setting3'), (True, None)), (1, 'setting6'), ((2, 'key'), ('value', 'value')), (2, 'doge'), ((3, 'wow'), ('', 'so much')), (0, 'group1'), ((1, 'baz'), ('bas', 'bars')), ((1, 'foo'), ('bar', 'bar')), ((1, 'nest'), ({'key': 'value'}, [...])), ((0, 'group2'), ({'abc': 12345, 'deep': {'id': 45}}, [...])), ((0, 'group3'), (None, [...]))], [(0, 'common'), ((1, 'setting1'), ('Value 1', 'Value 1')), ((1, 'setting2'), (200, None)), ((1, 'setting3'), (True, None)), (1, 'setting6'), ((2, 'key'), ('value', 'value')), (2, 'doge'), ((3, 'wow'), ('', 'so much')), (0, 'group1'), ((1, 'baz'), ('bas', 'bars')), ((1, 'foo'), ('bar', 'bar')), ((1, 'nest'), ({'key': 'value'}, [...])), ((0, 'group2'), ({'abc': 12345, 'deep': {'id': 45}}, [...])), ((0, 'group3'), (None, [...]))], [(0, 'common'), ((1, 'setting1'), ('Value 1', 'Value 1')), ((1, 'setting2'), (200, None)), ((1, 'setting3'), (True, None)), (1, 'setting6'), ((2, 'key'), ('value', 'value')), (2, 'doge'), ((3, 'wow'), ('', 'so much')), (0, 'group1'), ((1, 'baz'), ('bas', 'bars')), ((1, 'foo'), ('bar', 'bar')), ((1, 'nest'), ({'key': 'value'}, [...])), ((0, 'group2'), ({'abc': 12345, 'deep': {'id': 45}}, [...])), ((0, 'group3'), (None, [...]))]]"

# format(test)