name: tests-check
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest 
    steps:
    - name: linter-check
      run: |
        pip install poetry
        make lint
    - name: test-check
      run: |
        pip install pytest    
        make test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: c66fbbaa98f42743839400fda3cdbc9f410bd511854f288834b44bd425202c34
      with:
        coverageCommand: make test-coverage
        debug: true